# https://beta.ruff.rs
name: ruff
on:
  push:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install --user ruff
      - run: ruff check --output-format=github .
